# Generated by Django 5.2.6 on 2025-10-06 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh_key', models.TextField(help_text='P256DH public key')),
                ('auth_key', models.TextField(help_text='Auth secret')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('daily_checkin', 'Daily Check-in'), ('evening_wrapup', 'Evening Wrap-up'), ('reminder', 'Reminder'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(default='/', max_length=500)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time', models.DateTimeField(help_text='When to send the notification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('snoozed', 'Snoozed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('snooze_duration_minutes', models.IntegerField(default=30, help_text='Default snooze duration in minutes')),
                ('snooze_count', models.IntegerField(default=0, help_text='Number of times this notification has been snoozed')),
                ('max_snooze_count', models.IntegerField(default=3, help_text='Maximum number of times this can be snoozed')),
                ('original_scheduled_time', models.DateTimeField(blank=True, help_text='Original scheduled time before any snoozes', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='iCal RRULE format', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Notification',
                'verbose_name_plural': 'Scheduled Notifications',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['user', 'status', 'scheduled_time'], name='notificatio_user_id_d8f2f0_idx'), models.Index(fields=['scheduled_time', 'status'], name='notificatio_schedul_16a3fc_idx')],
            },
        ),
    ]
