# Generated by Django 5.2.7 on 2025-10-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('digest', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuantizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('parameter_size', models.CharField(blank=True, max_length=20, null=True)),
                ('llm_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ollama_service.llmmodel')),
                ('parent_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_models', to='ollama_service.llmmodel')),
                ('families', models.ManyToManyField(blank=True, related_name='variants', to='ollama_service.modelfamily')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ollama_service.modelfamily')),
                ('quantization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ollama_service.quantizationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='LLMModelCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ollama_service.capability')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='ollama_service.llmmodel')),
            ],
            options={
                'unique_together': {('llm_model', 'capability')},
            },
        ),
    ]
