# Generated by Django 5.2.7 on 2025-10-15 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('model', models.CharField(default='qwen3', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='You are an Intelligent AI assistant.')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature (default: 0.8 by Ollama)', null=True)),
                ('max_tokens', models.IntegerField(blank=True, default=2000, null=True)),
                ('top_k', models.IntegerField(blank=True, help_text='Top-k sampling (default: 40)', null=True)),
                ('top_p', models.FloatField(blank=True, help_text='Top-p sampling (default: 0.9)', null=True)),
                ('repeat_penalty', models.FloatField(blank=True, help_text='Repeat penalty (default: 1.1)', null=True)),
                ('seed', models.IntegerField(blank=True, help_text='Random seed for reproducibility', null=True)),
                ('num_predict', models.IntegerField(blank=True, help_text='Max tokens to generate', null=True)),
                ('num_ctx', models.IntegerField(blank=True, help_text='Context window size', null=True)),
                ('tools_enabled', models.JSONField(blank=True, default=list)),
                ('rag_enabled', models.BooleanField(default=False)),
                ('rag_sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_history', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('human', 'Human'), ('ai', 'AI'), ('system', 'System'), ('function', 'Function'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, max_length=100)),
                ('token_count', models.IntegerField(default=0)),
                ('finish_reason', models.CharField(blank=True, choices=[('stop', 'Stop'), ('length', 'Length'), ('tool_calls', 'Tool Calls'), ('content_filter', 'Content Filter'), ('error', 'Error')], max_length=20)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('feedback', models.IntegerField(blank=True, choices=[(1, 'Positive'), (-1, 'Negative')], null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='langchain_chat.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='langchain_chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('thought', models.TextField()),
                ('action', models.CharField(blank=True, max_length=100)),
                ('action_input', models.JSONField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_steps', to='langchain_chat.chatsession')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_steps', to='langchain_chat.message')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField()),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='langchain_chat.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='langchain_chat.chatsession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-updated_at'], name='langchain_c_updated_b36a64_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='langchain_c_user_id_75613a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='langchain_c_session_5bcfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tool_call_id'], name='langchain_c_tool_ca_5d817a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstep',
            unique_together={('message', 'step_number')},
        ),
    ]
